import type { Metadata } from "next";
import { Inter } from "next/font/google"
import "./globals.css";
import { Sidebar } from "./components/sidebar";
import { Header } from './components/header';

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-auto min-h-screen bg-[#F7F7F7]">
        <Header />
          <Sidebar />
          <main className="flex-1 ml-[246px] pt-13 flex flex-col"><div className="flex flex-col flex-1">{children}</div></main>
        </div>
      </body>
    </html>
  );
}
